![SVD](images/SVDD.png)

Note that S is diagonal matrix with 𝜎1> 𝜎2 >....𝜎k >𝜎k+1...

In [1]:
import numpy as np
from numpy.linalg import svd
from numpy import array
from numpy import diag
from numpy import zeros

In [2]:
#Lets show how we can calculate SVD with numpy, and show above equation is true.
#Lets define a 3x2 matrix as:
X = array([[1, 2], [3, 4], [5, 6]])
#Now using numpys linalg library, decomposite this matrix:
U, s, VT = svd(X)
print(U.shape)
print(s.shape)
print(VT.shape)

(3, 3)
(2,)
(2, 2)


In [3]:
#Notice that in order to reconstruct matrix M, we need s as a mxn matrix but numpy's svd command gives us as a flat (2,). In this case we need it to be diagonal 3x2 matrix
#First, create a 3x2(mxn) matrix
Sigma=zeros(X.shape)  # X is our original mxn matrix
print("3x2 Sigma Matrix:\n",Sigma,"\n")
#And lets diagonalize s
s=diag(s)
print("Diagonalized s matrix:\n",s)

3x2 Sigma Matrix:
 [[0. 0.]
 [0. 0.]
 [0. 0.]] 

Diagonalized s matrix:
 [[9.52551809 0.        ]
 [0.         0.51430058]]


In [4]:
#Now we need our diagonalized s matrix as 3x2 matrix
#for this, we put s in Sigma's first n rows, which n is s' number of rows.
Sigma[:s.shape[0]]=s
print(Sigma)

[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]


![SVD](images\sinSigma.png)

In [5]:
#Since we have a 3x2 (mxn) diagonal Sigma matrix now, we simply reconstruct our original matrix X
X_rec=U@Sigma@VT
print("Reconstructed matrix:\n",X_rec)

Reconstructed matrix:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


   ## Dimensionality Reduction with SVD

We can approximate a huge matrix as sum of rank k matrixes

![SVD](images\sigma.png)

Rank is maximum number of linearly independent columns of matrix.

In [6]:
#We can show this on our matrix X:
#Lets define k as 1
k=1
X_approximate=U@Sigma[:,:k]@VT[:k,:]


Note that we used k as a column index for Sigma, and row index for VT, in order to do dot product between matrixes.
![SVD](images\sigma2.png)

In [7]:
X_approximate
#We can see that for rank=1, our approximation for our original matrix is:

array([[1.35662819, 1.71846235],
       [3.09719707, 3.92326845],
       [4.83776596, 6.12807454]])

In [8]:
#For higher k, our approximation will be more accurate:
k=2
X_approximate=U@Sigma[:,:k]@VT[:k,:]
X_approximate
# We reconstructed our original matrix with k=2, notice that original matrix X has 2 linearly independent columns.

array([[1., 2.],
       [3., 4.],
       [5., 6.]])